exports.el_cart = {
  add_item: ".btn_primary",
  back_home_btn: '[data-test="back-to-products"]',
  error_message: '[data-test="error"]',
  adv_btn: ".btn_action",
  cart_btn: ".shopping_cart_link",
  cancel_btn: '[data-test="cancel"]',
  item_name: ".inventory_item_name ",
  item_price: ".inventory_item_price",
  last_name: '[data-test="lastName"]',
  logout: "#logout_sidebar_link",
  menu: "#react-burger-menu-btn",
  message_success: ".complete-header",
  name: '[data-test="firstName"]',
  postal_code: '[data-test="postalCode"]',
  remove_btn: ".btn_secondary",
  sum_items: ".summary_subtotal_label",
  rate_item: ".summary_tax_label",
  total_price: ".summary_total_label",
};
